### ISSUE TITLE
List is out of sync

### ISSUE THREAD

**Issue by imahbub** [The-Penguins-Club/bd-startups#31]
Many missing entries can be seen, needs attention to this. Also, is there a way to automate things? Let's discuss.

**Comment by fazlerabbi37** [comment]
automate as to check if the site is up for an entry?

**Comment by imahbub** [comment]
> automate as to check if the site is up for an entry?

We just need an API and @ahmubashshir GH action skills here

**Comment by ahmubashshir** [comment]
TBH, parsing markdown is almost like scrapping html for data... we can do it like this

```toml
# README.en.toml
[[startups]]
name = '10 Minute School'
url = 'https://10minuteschool.com/'
updated = '2022-02-10T11:30:00+0600'
```
and generate README.en.md from that, after checking validity of data.
